Expression ordering made TimSort fail
UnitTestBot/ksmt pull request #93
Opened 2023-03-28 20:55 UTC by niyaznigmatullin

The following exception happened:
```
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
	at org.ksmt.expr.rewrite.simplify.ExpressionOrderingKt.ensureExpressionsOrder(ExpressionOrdering.kt:40)
	at org.ksmt.expr.rewrite.simplify.BoolSimplificationKt.simplifyAnd(BoolSimplification.kt:504)
	at org.ksmt.KContext.mkAnd(KContext.kt:680)
	at org.ksmt.KContext.mkAnd$default(KContext.kt:674)
```

The PR adds the test to show the failure and fixes the issue

2023-03-29 08:30 UTC, Saloed requested changes

2023-03-30 08:45 UTC, niyaznigmatullin commented on ksmt-core/src/test/kotlin/org/ksmt/expr/rewrite/simplify/ExpressionOrderingTest.kt
> +                            value2,
Fixed this

2023-03-30 10:15 UTC, Saloed commented on ksmt-core/src/test/kotlin/org/ksmt/expr/rewrite/simplify/ExpressionOrderingTest.kt
> +        KConst(ctx, KIntNumDecl(ctx, "1")),
Unmanaged means created using internal constructor and without use of the corresponding mkX method of KContext. The main difference is that if we invoke the constructor directly we bypass expression interning.

2023-03-30 11:10 UTC, niyaznigmatullin commented on ksmt-core/src/test/kotlin/org/ksmt/expr/rewrite/simplify/ExpressionOrderingTest.kt
> +        KConst(ctx, KIntNumDecl(ctx, "1")),
Thanks. I think I fixed it

2023-03-30 11:54 UTC, Saloed approved these changes

2023-03-30 12:15 UTC, merged